lista = ('Lápis', 1.75, 'Borracha', 2.00, 'Caderno', 15.00, 'Estojo', 25.00,
         'Transferidor', 4.20, 'Compasso', 9.99, 'Mochila', 120.32,
         'Canetas', 22.30, 'Livros', 34.90)
print('_' * 33)
print('        Listagem de preço')
print('-' * 33)
print(f'{lista[0]}....................R$   {lista[1]}')
print(f'{lista[2]}.................R$   {lista[3]:.2f}')
print(f'{lista[4]}..................R$  {lista[5]:.2f}')
print(f'{lista[6]}...................R$  {lista[7]:.2f}')
print(f'{lista[8]}.............R$   {lista[9]:.2f}')
print(f'{lista[10]}.................R$   {lista[11]:.2f}')
print(f'{lista[12]}..................R$ {lista[13]:.2f}')
print(f'{lista[14]}..................R$  {lista[15]:.2f}')
print(f'{lista[16]}...................R$  {lista[17]:.2f}')
print('-' * 33)